#ifndef ACCOUNTDLL_GLOBAL_H
#define ACCOUNTDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACCOUNTDLL_LIBRARY)
#  define ACCOUNTDLL_EXPORT Q_DECL_EXPORT
#else
#  define ACCOUNTDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // ACCOUNTDLL_GLOBAL_H
