#ifndef PININTERFACE_GLOBAL_H
#define PININTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PININTERFACE_LIBRARY)
#  define PININTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define PININTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // PININTERFACE_GLOBAL_H
